### ISSUE TITLE
[FEAT]: Set $HOME in postflight plist modification in salt cask

### ISSUE THREAD

**Issue by lmf-mx** [cdalvaro/homebrew-tap#93]
### Description

The process spawned by the minion plist has no HOME environment variable set for the root user it runs as. This is not seen when running from the minion with salt-call.

When running from the master, due to the change in brew in https://github.com/Homebrew/brew/commit/4184546067cb33e8d4de3c0ce9b5e6f1ebf7daca `pkg.installed` fails with an error about missing HOME passed in from brew. The lack of a HOME variable can be seen by running `salt 'minion' environ.items` from a remote master.

I propose setting the HOME variable in the postflight task in addition to the HOMEBREW_PREFIX variable. On an M2 on Sonoma, this is `/var/root` for the root user. Alternatively, I manually set it to `/opt/salt` in the plist.

**Comment by cdalvaro** [comment]
Hi @lmf-mx, thank you for opening this issue. I know really well what are you talking about... I fixed this issue long time ago, but the fix was accepted recently https://github.com/saltstack/salt/pull/64924

So, hopefully, salt 3007 won't have this issue.

In the meantime, I think I can add the environment variable as a workaround for this issue. I'll remove it once salt 3007 is available.

**Comment by lmf-mx** [comment]
Hi @cdalvaro, I saw the PR you referenced. Maybe I'm missing something, but I don't see anything that sets the HOME variable in the spawned minions environment. The change in brew specifically tests for that now, aside from the HOMEBREW_PREFIX issue.

**Comment by cdalvaro** [comment]
> Hi @cdalvaro, I saw the PR you referenced. Maybe I'm missing something, but I don't see anything that sets the HOME variable in the spawned minions environment. The change in brew specifically tests for that now, aside from the HOMEBREW_PREFIX issue.

The fix can be a bit obscure, but in the end, the main problem was [here](https://github.com/saltstack/salt/pull/64924/files#diff-f2ead52475ed63b95fb21daf359178036609f56e8f8ca2f18fd23f38f0557db5L107-L112). In order to get the `brew` _prefix_, salt was asking `brew` for it, but running `brew` as `root`.

Now, the way to get the homebrew's prefix is a little more complex, looking first for the `HOMEBREW_PREFIX` env variable. Then, if it is not present, salt asks `brew` for its prefix, but this time _running the command as brew's owner user (with is `HOME` directory defined)_ instead of running as `root`.

**Comment by lmf-mx** [comment]
Thanks for the explanation. I follow now.
